### ISSUE TITLE
Uncaught module seuic-plugin-scanner.scanner already defined

### ISSUE THREAD

**Issue by densey** [mphumzi-mlotywa/seuic-plugin-scanner#2]
Uncaught module seuic-plugin-scanner.scanner already defined
cordova.js error.

Please help. We develop fair application with using AutoId Seuic. We have to get Seuic Laser Scanner Cordova App

**Comment by mphumzi-mlotywa** [comment]
Hi Densey,

If you still need some help with this...  here is a work-around in the two steps below:
1. Open "scannerapi" script on the the following directory in your app - 
C:\Users\...\<YourAppName>\platforms\android\platform_www\plugins\seuic-plugin-scanner\www\

2. Remove one of the duplicate code statements. please see below:
`cordova.define("seuic-plugin-scanner.scanner", function(require, exports, module) {
cordova.define("seuic-plugin-scanner.scanner", function(require, exports, module) {
    var exec = require('cordova/exec');
    module.exports = {
        openScanner: function() {
            exec(null, null, "Scanner", "openScanner", []);
        },
        closeScanner: function() {
            exec(null, null, "Scanner", "closeScanner", []);
        },
        startScan: function() {
            exec(null, null, "Scanner", "startScan", []);
        },
        stopScan: function() {
            exec(null, null, "Scanner", "stopScan", []);
        },
        setParam: function(paramId, value) {
            exec(null, null, "Scanner", "setParam", [paramId, value]);
        },
        setDecodeCallback: function(decodeCallback) {
            exec(decodeCallback, null, "Scanner", "setDecodeCallback", []);
        }
    };
});
});
`

Hope this helps,

Thanks & regards,
MM

**Comment by mphumzi-mlotywa** [comment]
Remove -:
`cordova.define("seuic-plugin-scanner.scanner", function(require, exports, module) { ...}:`

**Comment by densey** [comment]
Thanks works
